/**You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
  */

function findTheDifference(s: string, t: string): string {
    const hashMap: Map<string, number> = new Map();

    for(let i = 0; i < s.length; i++){
        let currChar: string = s[i];
        if(hashMap.has(currChar)){
            hashMap.set(currChar, hashMap.get(currChar)! + 1);
        }else{
            hashMap.set(currChar, 1);
        }
    }

    for(let i = 0; i < t.length; i ++){
        let currChar: string = t[i];

        if(hashMap.get(currChar)! <= 0 && hashMap.get(currChar) !== undefined){
            return currChar
        }
    }

    return ""
};